dist: trusty

language: rust

services: docker

sudo: required

# cache: cargo
cache:
  directories:
    - target
    - cargo

before_cache:
  # - chmod -R a+r $HOME/.cargo
  - sudo chown -R $USER cargo
  - sudo chown -R $USER target
  - chmod -R a+r cargo
  - chmod -R a+r target

notifications:
  email:
    on_success: never

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master
    - develop

before_install:
    - set -e
    # - rustup self update
    # - rustup install nightly-2018-02-14
    # - rustup default nightly-2018-02-14
# - rustup default nightly

install:
- sh ci/install.sh
- source ~/.cargo/env || true

script:
- bash ci/script.sh

after_script: set +e

env:
  global:
  - CRATE_NAME=blockchain

matrix:
    include:
        # - env: TARGET=x86_64-unknown-linux-gnu
        #   rust: nightly
        - env: TARGET=x86_64-unknown-linux-musl
          rust: nightly
        # - env: TARGET=x86_64-pc-windows-gnu
        #   rust: nightly

before_deploy:
    - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
      secure: "ATmRv2JtWff+isvT28cOVRXJAjDt/CDLgB/9y072TNeJiUaNYRKh8QdxlD9K/xaW3qxnj847C4PvOOWr/SOYlhJWIR/9rdt2XcG8BX2uSWZu6RavxB10I7YePahXeiHvix016PiOTJFr+lAoHOR3H9FFcSqN6Bv0azOMzFlhg9o/D/79rWKqpeY3zTKN9gFzGSDznd7xNoLBVMVW6hytA/Jgu2+hqZtQLc/+I+sqb0qdismZE4P6F+csc69W2OFQY0T+NUUggCZFlLoj+IfvVCROjKSd2itnsEOdmRLQnx1tEBeBx9nr9V4VccMkgiXLqtN8y+7jU5MLeUXRo4ikllNOA9XpxwD1jLykzDQVvTwDb3HyeSk5hmNDWKRIXP83ptE194Zn5/qAkYwetH2b0+iWy5dQkXNLvwm8EmidWujI9eAVilT2qfI1R0BtpWZTg8EvknogF/sXUMTuP64ZGFeaXmQe2Vv1zfPo1FHIxY/HLJaTp7iWkJw3j0+I9vMb2uEBtkv0Tcv340Br7fFBEtSgdDDy3P65D/sgXQxp5cZXXsVTQTKwUJAWwETUoVQIKN2Y60yGX6XEcI0mVyVWG8woOuWk/niRs3oE9OYJ2Nk2zlXhX+Y1wEHUPkTxABbByu8rDIu6RTag8FXa5Qzkbhc87udV/f3KoVu6ck+m9H8="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
