[package]
name = "invoice_generator"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
chrono = "0.4.2"
clap = "2.31.1"
env_logger = "0.5.3"
log = "0.4.1"

client = { path = "../../lib/client" }
cryptography = { path = "../../lib/cryptography" }
data = { path = "../../lib/data" }
