[package]
name = "partial-collision-test"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
bincode = "0.9.2"
sha2 = "0.7.0"
serde = "1.0.21"
serde_derive = "1.0.21"
